title: "Emil Khabiboulline"
description: "I'm a PhD student in the Department of Physics at Harvard, working on theory for quantum computing and quantum many-body physics: communication protocols and thermalization."
markdown: kramdown
plugins:
  - jekyll-sitemap
